"""add status and checks

Revision ID: 235f88d6e648
Revises: 9a622e85129a
Create Date: 2026-10-06 18:05:55.345746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235f88d6e648'
down_revision: Union[str, Sequence[str], None] = '9a622e85129a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_target_id'), 'checks', ['target_id'], unique=False)
    op.add_column('targets', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('targets', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'last_checked_at')
    op.drop_column('targets', 'status')
    op.drop_index(op.f('ix_checks_target_id'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
